// Defined constant for actions
export const CLEAR_DATA_WEATHER = 'CLEAR_DATA_WEATHER';
export const FETCHING_WEATHER_SUCCESS = 'FETCHING_WEATHER_SUCCESS';
export const FETCHING_WEATHER_FAILURE = 'FETCHING_WEATHER_FAILURE';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const FETCHING_LOCATION_SUCCESS = 'FETCHING_LOCATION_SUCCESS';
export const FETCHING_LOCATION_FAILURE = 'FETCHING_LOCATION_FAILURE';
